name: bangladesh_landmarks
description: Bangladesh Landmarks management app for CSE 489 assignment.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  http: ^1.1.0
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  image_picker: ^1.0.7
  image: ^4.0.17
  path_provider: ^2.0.11
  sqflite: ^2.2.8+1
  path: ^1.8.3
  flutter_slidable: ^2.0.0
  cached_network_image: ^3.2.3
  flutter_map_marker_cluster: ^1.0.0
  geolocator: ^10.1.0
  shared_preferences: ^2.2.2
  clerk_flutter: ^0.0.13-beta

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

dependency_overrides:
  http: ^1.1.0
flutter:
  uses-material-design: true
